/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.raven.form;

import Tabla.imprimirDatos;
import com.raven.detalles.detallesAceptado;
import com.raven.detalles.detallesFinalizado;
import com.raven.detalles.detallesPendiente;
import java.util.ArrayList;

/**
 *
 * @author RAVEN
 */
public class Form_2 extends javax.swing.JPanel {
    ArrayList <Integer> ArrayIdSolicitudes;
    /**
     * Creates new form Form_1
     */
    public Form_2() {
        
        initComponents();
        imprimirDatos x = new imprimirDatos();
        ArrayIdSolicitudes=x.visualizar_tabla_gastos(tableSolicitudes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panelBorder1 = new com.raven.swing.PanelBorder();
        jLabel2 = new javax.swing.JLabel();
        spTable = new javax.swing.JScrollPane();
        tableSolicitudes = new com.raven.swing.Table();

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(106, 106, 106));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Form 2");

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(127, 127, 127));
        jLabel2.setText("Solicitudes");

        spTable.setBorder(null);

        tableSolicitudes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Profesional", "Descripcion", "Monto Solicitado", "Fecha Solicitud", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableSolicitudes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSolicitudesMouseClicked(evt);
            }
        });
        spTable.setViewportView(tableSolicitudes);

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(spTable, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spTable, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(125, 125, 125))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableSolicitudesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSolicitudesMouseClicked
        // TODO add your handling code here:
         if (evt.getClickCount() == 2) {
    int lastColumnIndex = tableSolicitudes.getColumnCount() - 1; // Última columna
    int row = tableSolicitudes.getSelectedRow();
    
    // Verificar si la fila y la columna son válidas
    if (row >= 0 && row < tableSolicitudes.getRowCount()) {
        int id = ArrayIdSolicitudes.get(row); // Obtener el ID
        
        Object value = tableSolicitudes.getValueAt(row, lastColumnIndex);
        
        if (value != null && value.toString().equalsIgnoreCase("Aceptado")) {
            // Abrir el JFrame detallesAceptado
            detallesAceptado DatosPanelAceptado = new detallesAceptado();
            DatosPanelAceptado.setDatosSolicitudPago(id);
            DatosPanelAceptado.setLocationRelativeTo(null);
            DatosPanelAceptado.setVisible(true);
        } else if (value != null && value.toString().equalsIgnoreCase("Pendiente")) {
            // Abrir el JFrame detallesPendiente
            detallesPendiente DatosPanelPendiente = new detallesPendiente();
            DatosPanelPendiente.setDatosSolicitud(id);
            DatosPanelPendiente.setLocationRelativeTo(null);
            DatosPanelPendiente.setVisible(true);
        }
        else if (value != null && value.toString().equalsIgnoreCase("Finalizado")) {
            // Abrir el JFrame detallesPendiente
            detallesFinalizado DetallesFinalizado = new detallesFinalizado();
            DetallesFinalizado.setDatosSolicitud(id);
            DetallesFinalizado.setLocationRelativeTo(null);
            DetallesFinalizado.setVisible(true);
        }
    }
}

    }//GEN-LAST:event_tableSolicitudesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private com.raven.swing.PanelBorder panelBorder1;
    private javax.swing.JScrollPane spTable;
    private com.raven.swing.Table tableSolicitudes;
    // End of variables declaration//GEN-END:variables
}
